import {test,expect} from '@playwright/test';
import {openSubjectSetup} from './onboarding.js';
test('setup, rating persistence, practice, themes and selection changes',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Know what to revise next.'})).toBeVisible();
 await expect(page.getByText('Your progress is saved locally.')).toBeVisible();
 await page.getByRole('button',{name:'Self assess'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('button',{name:'Start revising'})).toBeDisabled();
 await page.getByRole('checkbox',{name:'English Language',exact:true}).check();
 await page.getByRole('button',{name:'Start revising'}).click();
 await expect(page.locator('#subject-list > button')).toHaveCount(1);
 await page.locator('#subject-list > button').click();
 await expect(page.getByRole('navigation',{name:'How to revise this subject'})).toContainText('Self assess');
 await expect(page.getByRole('navigation',{name:'How to revise this subject'})).toContainText('Revise');
 await expect(page.getByRole('navigation',{name:'How to revise this subject'})).toContainText('Practise');
 await page.getByRole('button',{name:"Mark 3.1.1 as couldn't explain it",exact:true}).click();
 await page.reload();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('button',{name:"Mark 3.1.1 as couldn't explain it",exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Practice',exact:true}).click();
 await page.locator('textarea').first().fill('My saved answer');
 await page.getByRole('button',{name:'Reveal answer guide'}).first().click();
 await page.getByRole('button',{name:/^Choose 2 out of/}).first().click();
 await page.getByRole('button',{name:'Midnight',exact:true}).click();
 await page.reload();
 await expect(page.locator('html')).toHaveAttribute('data-theme','midnight');
 await page.getByRole('button',{name:'Practice',exact:true}).click();
 await expect(page.locator('textarea').first()).toHaveValue('My saved answer');
 await expect(page.getByRole('button',{name:/^Choose 2 out of/}).first()).toHaveAttribute('aria-pressed','true');
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Save and try again'}).first().click();
 await expect(page.locator('textarea').first()).toHaveValue('');
 await expect(page.locator('.attempt-history').first()).toContainText('1 previous attempt');
 await page.getByRole('button',{name:'All subjects'}).click();
 await page.getByRole('button',{name:'Change subjects'}).click();
 await expect(page.locator('html')).toHaveCSS('overflow','hidden');
 await expect(page.locator('body')).toHaveCSS('overflow','hidden');
 await page.getByRole('checkbox',{name:'Physics',exact:true}).check();
 await page.getByRole('checkbox',{name:'English Language',exact:true}).uncheck();
 await page.getByRole('button',{name:'Save subjects'}).click();
 await expect(page.locator('#subject-list > button')).toHaveCount(1);
 await expect(page.locator('#subject-list')).toContainText('Physics');
 await page.getByRole('button',{name:'Change subjects'}).click();
 await page.getByRole('checkbox',{name:'English Language',exact:true}).check();
 await page.getByRole('button',{name:'Save subjects'}).click();
 await page.locator('#subject-list > button').filter({hasText:'English Language'}).click();
 await expect(page.getByRole('button',{name:"Mark 3.1.1 as couldn't explain it",exact:true})).toHaveAttribute('aria-pressed','true');
 expect(errors).toEqual([]);
});
test('backup import and mobile layout',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openSubjectSetup(page);
 await page.getByRole('checkbox',{name:'English Language',exact:true}).check();await page.getByRole('button',{name:'Start revising'}).click();
 await page.locator('input[type=file]').setInputFiles('vce-tracker-progress.json');
 await page.locator('#subject-list > button').click();
 await expect(page.getByRole('button',{name:'Mark 3.1.1 as confident',exact:true})).toHaveAttribute('aria-pressed','true');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:'test-results/mobile-tracker.png',fullPage:false});
});
test('selected subjects use equal-sized dashboard cards in every theme',async({page})=>{
 await openSubjectSetup(page);
 for(const name of ['English Language','Physics','Chemistry','Psychology'])await page.getByRole('checkbox',{name,exact:true}).check();
 await page.getByRole('button',{name:'Start revising'}).click();
 for(const theme of ['Glass','Poster','Midnight','Notebook']){
  await page.getByRole('button',{name:theme,exact:true}).click();
  const widths=await page.locator('#subject-list > button').evaluateAll(cards=>cards.map(card=>card.getBoundingClientRect().width));
  expect(Math.max(...widths)-Math.min(...widths),theme+' card widths').toBeLessThan(1);
 }
});
