import React,{useRef} from 'react';
import {themeNames} from './Common.jsx';

export default function AppFooter({sync,status,theme,onTheme,onExport,onImportFile,onImportDesktop,onReset,active,isDesktop}){
 const fileInput=useRef(null);
 return <>
  <section className="sync" data-live={sync.connected?'true':sync.conflict?'warn':undefined}><p className="sync-head">Sync between computers</p><p className="sync-status" role="status">{sync.status}</p><div className="sync-actions">{sync.supported?<>{sync.connected?<><button className="ghost" onClick={sync.reload}>Reload from file</button><button className="ghost" onClick={sync.disconnect}>Stop syncing</button></>:<>{sync.pending&&<button className="ghost" onClick={()=>sync.connect(false,sync.pending)}>Reconnect sync file</button>}<button className="ghost" onClick={()=>sync.connect(true)}>Create sync file</button><button className="ghost" onClick={()=>sync.connect(false)}>Open sync file</button></>}</>:<p>Use Chrome or Edge for automatic file sync, or use the backup buttons below.</p>}</div></section>
  <footer><button className="ghost" onClick={onExport}>Save a backup file</button><button className="ghost" onClick={()=>isDesktop?onImportDesktop():fileInput.current.click()}>Load a backup file</button>{!isDesktop&&<input hidden type="file" ref={fileInput} accept=".json,application/json" onChange={event=>{onImportFile(event.target.files[0]);event.target.value='';}}/>}<div className="footer-rating-actions"><button className="ghost danger" onClick={onReset}>Clear ratings</button><div className="theme-picker"><span className="theme-picker-label">Theme</span><div className="theme-options" role="group" aria-label="Theme">{themeNames.map(name=><button className="theme-option" key={name} aria-pressed={theme===name} onClick={()=>onTheme(name)}>{name[0].toUpperCase()+name.slice(1)}</button>)}</div></div></div><span className="status" role="status">{status}</span><p className="colophon">Shift-click a rating to step backwards. {active.reduce((count,subject)=>count+subject.points.length,0)} points across {active.length} selected subjects.</p></footer>
 </>;
}
